apiVersion: v1
kind: Service
metadata:
  name: weather-app
  namespace: weather-app  # Add this line
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: weather-app

