apiVersion: v1
kind: Service
metadata:
  name: weather-app
  namespace: weather-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30007  # Choose any available NodePort
  selector:
    app: weather-app

